# Generated by Django 5.0.7 on 2024-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gymbuddy", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutcategory",
            name="image",
            field=models.ImageField(upload_to="workout_categories"),
        ),
        migrations.AlterField(
            model_name="workoutexercise",
            name="image",
            field=models.ImageField(upload_to="workout_exercises"),
        ),
    ]
